spring:
  datasource:
    url: jdbc:h2:mem:testdb/test
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
        show-sql: false # Turn on only when its needed

  h2.console.enabled: true